[package]
name = "loony-rpc"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
loony-core = { path = "../core" }
loony-storage = { path = "../storage" }
loony-metadata = { path = "../metadata" }
axum.workspace = true
tokio.workspace = true
reqwest.workspace = true
futures.workspace = true
bytes.workspace = true
async-trait.workspace = true
subtle.workspace = true
thiserror.workspace = true
tracing.workspace = true
serde.workspace = true
openraft.workspace = true

[dev-dependencies]
tempfile.workspace = true
time.workspace = true
