[package]
name = "s3-api"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
s3-core = { path = "../core" }
s3-object = { path = "../object" }
s3-observability = { path = "../observability" }
s3-metadata = { path = "../metadata" }
s3-storage = { path = "../storage" }
s3-auth = { path = "../auth" }
axum.workspace = true
tower.workspace = true
tower-http = { workspace = true, features = ["request-id", "trace", "cors"] }
http.workspace = true
tokio.workspace = true
futures.workspace = true
bytes.workspace = true
time.workspace = true
tracing.workspace = true
uuid.workspace = true
serde.workspace = true
quick-xml.workspace = true

[dev-dependencies]
tempfile.workspace = true
http-body-util = "0.1"
sha2.workspace = true
