[package]
name = "loony-server"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "loony-server"
path = "src/main.rs"

[dependencies]
loony-core = { path = "../core" }
loony-cluster = { path = "../cluster" }
loony-storage = { path = "../storage" }
loony-observability = { path = "../observability" }
loony-metadata = { path = "../metadata" }
loony-object = { path = "../object" }
loony-api = { path = "../api" }
loony-rpc = { path = "../rpc" }
tokio.workspace = true
clap.workspace = true
dotenvy.workspace = true
thiserror.workspace = true
tracing.workspace = true
axum.workspace = true
sha2.workspace = true
time.workspace = true
openraft.workspace = true
